### ISSUE TITLE
resize_bilinear no found on iOS

### ISSUE THREAD

**Issue by jst000000** [xuduo35/ncnn-mtcnn-facenet#2]
the method resize_bilinear no found on iOS

**Comment by xuduo35** [comment]
Can you paste the exact error message? Function resize_bilinear is from ncnn. Make sure you pass the right parameter types.

**Comment by jst000000** [comment]
it my mistake，my ncnn framework has no resize_bilinear method,i download the new ncnn framework now and it`s work,it run very good but cpu is more than 180% in iPhone 6,i think it will use all my cpu when i use neon

**Comment by guanbo123456** [comment]
我也遇到同样问题，请问ncnn用的是什么版本？
<img width="309" alt="image" src="https://user-images.githubusercontent.com/16915416/53089718-5155b680-3548-11e9-86c0-fc8f3836995a.png">

**Comment by jst000000** [comment]
换最新版本的就好了
