### ISSUE TITLE
facenet

### ISSUE THREAD

**Issue by jiangxiluning** [xuduo35/ncnn-mtcnn-facenet#3]
你好，请问你的 facenet 是如何转到 ncnn的，我用 TensorFlow2ncnn 总是报错

**Comment by xuduo35** [comment]
不好意思，邮件里回复错了，facenet我是在deepinsight里找的，忘了做转换还是原来就是可以用的，有转换的应该也很顺利，如果有的话你可以试试找找mxnet之类的版本。mtcnn的话，转换的cpp程序是ncnn的issues里找的，ncnn自带的有些问题，不知道新版本怎么样。
