### ISSUE TITLE
ncnn-mtcnn-facenet/iOS/FunAlbum/opencv2.framework/Headers/core/operations.hpp:65:16: 'ext/atomicity.h' file not found

### ISSUE THREAD

**Issue by guanbo123456** [xuduo35/ncnn-mtcnn-facenet#4]
ncnn-mtcnn-facenet/iOS/FunAlbum/opencv2.framework/Headers/core/operations.hpp:65:16: 'ext/atomicity.h' file not found

<img width="683" alt="image" src="https://user-images.githubusercontent.com/16915416/52839885-83bf7800-3132-11e9-9dc1-4c0bd0452513.png">

<img width="747" alt="image" src="https://user-images.githubusercontent.com/16915416/52839946-b36e8000-3132-11e9-896f-e7fba5165ea7.png">

**Comment by xuduo35** [comment]
I didn't meet with this issue, you can refer to https://stackoverflow.com/questions/13037659/opencv-build-issue-cant-find-ext-atomicity-h

**Comment by guanbo123456** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/16915416/52990026-26346f80-3441-11e9-8c77-4754c9331eb0.png">
可能是库的问题，能把这三个库上传一下吗？或者QQ534945456

**Comment by xuduo35** [comment]
You can get it from github ncnn & opencv project releases page.

**Comment by guanbo123456** [comment]
可能和XCode版本有关系？问下你用的XCode什么版本？

**Comment by xuduo35** [comment]
Version 10.1 (10B61)
