### ISSUE TITLE
请问ncnn用的什么版本？

### ISSUE THREAD

**Issue by guanbo123456** [xuduo35/ncnn-mtcnn-facenet#6]
请问ncnn用的什么版本？
![](https://user-images.githubusercontent.com/16915416/53089718-5155b680-3548-11e9-86c0-fc8f3836995a.png)

**Comment by xuduo35** [comment]
大概去年10月份下载最新的你去找一下。

**Comment by guanbo123456** [comment]
还是有问题，能不能把工程文件给我发一份，guanbo123456@sina.com

**Comment by xuduo35** [comment]
实在不行，你就找一个ncnn把这个函数拷贝过去吧。
