### ISSUE TITLE
CPU占用180%，有没有优化方法？

### ISSUE THREAD

**Issue by guanbo123456** [xuduo35/ncnn-mtcnn-facenet#7]
CPU占用180%，有没有优化方法？
<img width="265" alt="image" src="https://user-images.githubusercontent.com/16915416/53777238-ac69af00-3f33-11e9-9c12-66055f365c41.png">

**Comment by xuduo35** [comment]
模型都是训练好的，很难优化了。可以从增大检测间隔这种办法处理吧。
